spring:
 datasource:
  url: jdbc:mysql://localhost:3306/minorProject1?createDatabaseIfNotExist=true
  username: root
  password: monu@2001
 jpa:
  hibernate.ddl-auto: update
  show-sql: true 
  
server:
 port: 8085
 
custom_property:
 secret_key: 8ff8fg8erhrhr
 
book:
 maxAllowedDays: 14